apiVersion: v1
kind: PersistentVolume
metadata:
  name: spcpro-projects-pv
  labels:
    app: spcpro-projects
    namespace: spcpro
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfs-storage
  volumeMode: Filesystem
  local:
    path: /mnt/glusterfs/spcpro-projects
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - moccluster1
                - moccluster2
