apiVersion: v1
kind: Secret
metadata:
  name: spcpro-projects-secrets
  namespace: spcpro
type: Opaque
stringData:
  # Credenciales admin iniciales (se crea si el usuario no existe)
  SPCPRO_DEFAULT_ADMIN_EMAIL: rodrigo.mocca@spcpro.com
  SPCPRO_DEFAULT_ADMIN_PASSWORD: SpCpRo2026!
